INSERT INTO notion (NameNotion, Skill, ProgLang, Software, Maths, Physics) 
VALUES ('Tinkercad', false, false, true, false, false),
('Arduino Uno', false, false, true, false, false),
('C Arduino', true, true, false, false, false),
('Continuous current', false, false, false, false, true),
('Alternating current', false, false, false, false, true),
('Signal processing', false, false, true, false, false),
('Jupyter Notebook', false, false, true, false, false),
('Python', true, true, false, false, false),
('Laws of static', false, false, false, false, true),
('Laws of dynamic', false, false, false, false, true),
('Mechanics', true, false, false, false, true),
('Computer Aided Conception', true, false, true, false, false),
('Fusion360', true, false, true, false, false),
('3D printing', true, false, false, false, false),
('Cura', false, false, true, false, false),
('Lean management', true, false, true, false, false),
('MySQL', true, true, false, false, false),
('MicrosoftSQL', true, true, false, false, false),
('Relationnal databases', true, false, false, false, false),
('Merise Method', false, false, false, false, false),
('Data analysis', false, false, true, false, false),
('Statistics', false, false, false, true, false),
('Thermodynamics', false, false, false, false, true),
('Materials strenght', false, false, false, false, true),
('Revit', false, false, true, false, false),
('Differential equations', false, false, false, true, false),
('Probabilities', false, false, false, true, false),
('Numeric sequences', false, false, false, true, false),
('Complex numbers', false, false, false, true, false),
('Cartesian geometry', false, false, false, true, false),
('Vectorial geometry', false, false, false, true, false),
('Matrix', false, false, false, true, false),
('Arithmetics', false, false, false, true, false),
('Embedded system', false, false, false, false, false),
('C', true, true, false, false, false),
('C++', true, true, false, false, false),
('C#', true, true, false, false, false),
('.NET', true, true, false, false, false),
('UML Conception', false, false, false, false, false),
('Procedural programming', false, false, false, false, false),
('Oriented Object Programming', true, false, false, false, false),
('IS architecture & networks', true, false, true, false, false),
('CCNA Certification', true, false, true, false, false),
('Cisco Packet Tracer', false, false, true, false, false),
('Cybersecurity', false, false, false, false, false),
('Game theory', false, false, false, true, false),
('Programming Paradigms', false, false, false, false, false),
('English', false, false, false, false, false),
('Cryptography', false, false, false, false, false),
('Graph theory', false, false, false, true, false),
('Database Mangement Systems', false, false, false, false, false),
('Group Policy Objects', false, false, false, false, false),
('Cloud computing', false, false, false, false, false),
('Problem complexity', false, false, false, false, false),
('Problem categories', false, false, false, false, false),
('Algorithmics', false, false, false, true, false),
('Heuristics & meta heuristics', false, false, false, false, false),
('Linear programming', false, false, false, true, false),
('Best solution search algorithms', false, false, false, false, false),
('Operation research', false, false, false, false, false),
('Machine learning', true, false, false, false, false),
('Data processing', false, false, false, false, false),
('Model creation & training', false, false, false, false, false),
('Model performance analysis', false, false, false, false, false),
('Regression models', false, false, false, false, false),
('Classifier models', false, false, false, false, false),
('HTML', true, true, false, false, false),
('CSS', true, true, false, false, false),
('JavaScript', true, true, false, false, false),
('PHP', true, true, false, false, false),
('Smarty', true, true, false, false, false),
('APIs', true, false, false, false, false),
('Rest APIs', false, true, false, false, false),
('GraphQL APIs', false, true, false, false, false),
('UX/UI Design', true, false, false, false, false),
('RobotFramework', false, true, false, false, false),
('Selenium', true, true, false, false, false),
('Electrical circuits', false, false, false, false, false),
('Fourier\'s law', false, false, false, true, false),
('Latis pro', false, false, true, false, false),
('Needs assessment', true, false, false, false, false),
('Boolean algebra', false, false, false, true, false),
('PowerApps', false, false, true, false, false),
('PowerBi', false, false, true, false, false),
('PowerAutomate', false, true, false, false, false),
('Blender', true, false, true, false, false),
('Unity', true, false, true, true, false),
('Team work', true, false, false, true, false),
('Project management', true, false, false, true, false);

INSERT INTO bloc (NameBloc, NthYear, DescriptionBloc, Duration, StatusBloc) 
VALUES ('Functions study', 'Year 1', 'Basics of functions study and analysis, and some basic maths. ', '2-3 weeks', 'Done'),
('Electricity & algorithmics', 'Year 1', 'Learn the functionning of electrical circuits and transistors as logical gates. Understand boolean algebra and solve boolean equations. Use tinkercad and C Arduino to simulate circuits and give digital feedbacks to user ', '3-4 weeks', 'Done'),
('Waves physics & signal', 'Year 1', 'Study alternating current and waves physics in electricity and signal processing. Learn how to modulate a signal, and transform it from analog to numerical with Fourier\'s law. Study the functionning of basic ecircuit elements and a condensator', '3-4 weeks', 'Done'),
('Mechanics', 'Year 1', 'Study the laws of dynamics in two-dimensional cartesian and polar coordinates system, determine trajectories, speed and external forces', '1 month', 'Done'),
('Industry', 'Year 1', 'Follow the case the study of a component box, from the needs assesment report and 3D conception to the production planning and quality control', '1 month', 'Done'),
('Databases', 'Year 1', 'Modelizing a relationnal database, building it and sending requests', '1 month', 'Done'),
('Thermodynamics & materials strenght', 'Year 1', 'Following a clients constraints to build a "container house". Make a materials strenght and thermodynamics study to choose the most fitted materials and modelize the house using Revit ', '1 month', 'Done'),
('Embedded systems', 'Year 2', 'Make and embedded circuit to analyze environmental factors (humidity, light, temperature). Store datas in and read from ROM', '1 month', 'Done'),
('Oriented Object Programming', 'Year 2', 'Learn about Oriented Object Programming with C++. Design an app with .NET to let an ordinary user communicate with a database', '5-6 weeks', 'Done'),
('SI Infrastructure & networks', 'Year 2', 'TODO', '1 month', 'Done'),
('Web development', 'Year 2', 'Learn the basis of web development to make a web application. Certificats SSh nanana', '5-6 weeks', 'Done'),
('Fundamental sciences', 'Year 3', 'TODO', '2 weeks', 'Done'),
('Information systems & security', 'Year 3', 'TODO', '2 weeks', 'Done'),
('Advanced algorithmics & combinatory', 'Year 3', 'TODO', '3 weeks', 'Done'),
('AI & machine learning', 'Year 3', 'TODO', '3 weeks', 'Done'),
('Software engineering', 'Year 3', 'TODO', '5 weeks', 'To come'),
('Big Data', 'Year 3', 'TODO', '1 month', 'To come'),
('Comunicating embedded systems', 'Year 4 : Embedded Systems & IOTs', 'TODO', Null, 'To come'),
('Comunicating embedded systems', 'Year 4 : Artificial Intelligence & Big Data', 'TODO', Null, 'To come'),
('Cloud architectures & IOTs', 'Embedded Systems & IOt', 'TODO', Null, 'To come'),
('Distributed applications development', 'Year 4 : Embedded Systems & IOtS', 'TODO', Null, 'To come'),
('Distributed applications development', 'Year 4 : Artificial Intelligence & Big Data', 'TODO', Null, 'To come'),
('AI : Ethics', 'Year 4 : Artificial Intelligence & Big Data', 'TODO', Null, 'To come'),
('AI :  Deep learning', 'Year 4 : Artificial Intelligence & Big Data', 'TODO', Null, 'To come'),
('English', 'All', 'TODO', '2h/Week', 'On going'),
('Mathematics', 'All', 'TODO', '1day/week', 'On going');

INSERT INTO project (NameProject, DescriptionProject, StatusProject, LinkProject, Deadline, IDBloc) 
VALUES ('Safe tinkercad', 'TODO', 'Done', 'TODO', '3 weeks', (SELECT IDBloc from bloc WHERE NameBloc='Electricity & algorithmics')),
('Signal modulation', 'TODO', 'Done', 'TODO', '3 weeks', (SELECT IDBloc from bloc WHERE NameBloc='Waves physics & signal')),
('\'Fast&Furious\' case study', 'TODO', 'Done', 'TODO', '1 month', (SELECT IDBloc from bloc WHERE NameBloc='Mechanics')),
('SmartIO Box', 'TODO', 'Done', 'TODO', '1 month', (SELECT IDBloc from bloc WHERE NameBloc='Industry')),
('TODO Databases', 'TODO', 'Done', 'TODO', '3 weeks', (SELECT IDBloc from bloc WHERE NameBloc='Databases')),
('Container House', 'TODO', 'Done', 'TODO', '1 month', (SELECT IDBloc from bloc WHERE NameBloc='Thermodynamics & materials strenght')),
('World Wide Weather Watcher', 'TODO', 'Done', 'TODO', '1 month', (SELECT IDBloc from bloc WHERE NameBloc='Embedded systems')),
('Oriented Object Programming TODO', 'TODO', 'Done', 'TODO', '3 weeks', (SELECT IDBloc from bloc WHERE NameBloc='Oriented Object Programming')),
('FunkyTown', 'TODO', 'Done', 'TODO', '3 weeks', (SELECT IDBloc from bloc WHERE NameBloc='SI Infrastructure & networks')),
('StageFinder', 'TODO', 'Done', 'TODO', '1 month', (SELECT IDBloc from bloc WHERE NameBloc='Web development')),
('Vehicle Routing Problem', 'TODO', 'Done', 'TODO', '2 weeks', (SELECT IDBloc from bloc WHERE NameBloc='Advanced algorithmics & combinatory')),
('HumanForYou', 'TODO', 'Done', 'TODO', '2 weeks', (SELECT IDBloc from bloc WHERE NameBloc='AI & machine learning')),
('Portfolio Website', 'TODO', 'On going', 'TODO', Null, Null),
('Shepherd dog game', 'TODO', 'On going', 'TODO', Null, Null),
('Lethal Presentation', 'TODO', 'To come', 'TODO', Null, Null);

INSERT INTO nobl (IDBloc, IDNotion) 
VALUES ((SELECT IDBloc from bloc WHERE NameBloc='Electricity & algorithmics'), (SELECT IDNotion from notion WHERE NameNotion='Tinkercad')),
((SELECT IDBloc from bloc WHERE NameBloc='Electricity & algorithmics'), (SELECT IDNotion from notion WHERE NameNotion='Arduino Uno')),
((SELECT IDBloc from bloc WHERE NameBloc='Embedded systems'), (SELECT IDNotion from notion WHERE NameNotion='Arduino Uno')),
((SELECT IDBloc from bloc WHERE NameBloc='Electricity & algorithmics'), (SELECT IDNotion from notion WHERE NameNotion='C Arduino')),
((SELECT IDBloc from bloc WHERE NameBloc='Embedded systems'), (SELECT IDNotion from notion WHERE NameNotion='C Arduino')),
((SELECT IDBloc from bloc WHERE NameBloc='Embedded systems'), (SELECT IDNotion from notion WHERE NameNotion='Continuous current')),
((SELECT IDBloc from bloc WHERE NameBloc='Electricity & algorithmics'), (SELECT IDNotion from notion WHERE NameNotion='Continuous current')),
((SELECT IDBloc from bloc WHERE NameBloc='Waves physics & signal'), (SELECT IDNotion from notion WHERE NameNotion='Alternating current')),
((SELECT IDBloc from bloc WHERE NameBloc='Waves physics & signal'), (SELECT IDNotion from notion WHERE NameNotion='Signal processing')),
((SELECT IDBloc from bloc WHERE NameBloc='Waves physics & signal'), (SELECT IDNotion from notion WHERE NameNotion='Python')),
((SELECT IDBloc from bloc WHERE NameBloc='Waves physics & signal'), (SELECT IDNotion from notion WHERE NameNotion='Jupyter Notebook')),
((SELECT IDBloc from bloc WHERE NameBloc='Thermodynamics & materials strenght'), (SELECT IDNotion from notion WHERE NameNotion='Laws of static')),
((SELECT IDBloc from bloc WHERE NameBloc='Mechanics'), (SELECT IDNotion from notion WHERE NameNotion='Laws of dynamic')),
((SELECT IDBloc from bloc WHERE NameBloc='Mechanics'), (SELECT IDNotion from notion WHERE NameNotion='Mechanics')),
((SELECT IDBloc from bloc WHERE NameBloc='Industry'), (SELECT IDNotion from notion WHERE NameNotion='Computer Aided Conception')),
((SELECT IDBloc from bloc WHERE NameBloc='Industry'), (SELECT IDNotion from notion WHERE NameNotion='Fusion360')),
((SELECT IDBloc from bloc WHERE NameBloc='Industry'), (SELECT IDNotion from notion WHERE NameNotion='3D printing')),
((SELECT IDBloc from bloc WHERE NameBloc='Industry'), (SELECT IDNotion from notion WHERE NameNotion='Cura')),
((SELECT IDBloc from bloc WHERE NameBloc='Industry'), (SELECT IDNotion from notion WHERE NameNotion='Lean management')),
((SELECT IDBloc from bloc WHERE NameBloc='Web development'), (SELECT IDNotion from notion WHERE NameNotion='MySQL')),
((SELECT IDBloc from bloc WHERE NameBloc='Databases'), (SELECT IDNotion from notion WHERE NameNotion='MySQL')),
((SELECT IDBloc from bloc WHERE NameBloc='Oriented Object Programming'), (SELECT IDNotion from notion WHERE NameNotion='MicrosoftSQL')),
((SELECT IDBloc from bloc WHERE NameBloc='Information systems & security'), (SELECT IDNotion from notion WHERE NameNotion='MicrosoftSQL')),
((SELECT IDBloc from bloc WHERE NameBloc='Databases'), (SELECT IDNotion from notion WHERE NameNotion='Relationnal databases')),
((SELECT IDBloc from bloc WHERE NameBloc='Web development'), (SELECT IDNotion from notion WHERE NameNotion='Relationnal databases')),
((SELECT IDBloc from bloc WHERE NameBloc='Information systems & security'), (SELECT IDNotion from notion WHERE NameNotion='Relationnal databases')),
((SELECT IDBloc from bloc WHERE NameBloc='Oriented Object Programming'), (SELECT IDNotion from notion WHERE NameNotion='Relationnal databases')),
((SELECT IDBloc from bloc WHERE NameBloc='Databases'), (SELECT IDNotion from notion WHERE NameNotion='Merise Method')),
((SELECT IDBloc from bloc WHERE NameBloc='Databases'), (SELECT IDNotion from notion WHERE NameNotion='Data analysis')),
((SELECT IDBloc from bloc WHERE NameBloc='Embedded systems'), (SELECT IDNotion from notion WHERE NameNotion='Data analysis')),
((SELECT IDBloc from bloc WHERE NameBloc='AI & machine learning'), (SELECT IDNotion from notion WHERE NameNotion='Data analysis')),
((SELECT IDBloc from bloc WHERE NameBloc='Functions study'), (SELECT IDNotion from notion WHERE NameNotion='Statistics')),
((SELECT IDBloc from bloc WHERE NameBloc='AI & machine learning'), (SELECT IDNotion from notion WHERE NameNotion='Statistics')),
((SELECT IDBloc from bloc WHERE NameBloc='Mathematics'), (SELECT IDNotion from notion WHERE NameNotion='Statistics')),
((SELECT IDBloc from bloc WHERE NameBloc='Fundamental sciences'), (SELECT IDNotion from notion WHERE NameNotion='Statistics')),
((SELECT IDBloc from bloc WHERE NameBloc='Oriented Object Programming'), (SELECT IDNotion from notion WHERE NameNotion='Statistics')),
((SELECT IDBloc from bloc WHERE NameBloc='Thermodynamics & materials strenght'), (SELECT IDNotion from notion WHERE NameNotion='Thermodynamics')),
((SELECT IDBloc from bloc WHERE NameBloc='Thermodynamics & materials strenght'), (SELECT IDNotion from notion WHERE NameNotion='Materials strenght')),
((SELECT IDBloc from bloc WHERE NameBloc='Thermodynamics & materials strenght'), (SELECT IDNotion from notion WHERE NameNotion='Revit')),
((SELECT IDBloc from bloc WHERE NameBloc='Thermodynamics & materials strenght'), (SELECT IDNotion from notion WHERE NameNotion='Differential equations')),
((SELECT IDBloc from bloc WHERE NameBloc='Mechanics'), (SELECT IDNotion from notion WHERE NameNotion='Differential equations')),
((SELECT IDBloc from bloc WHERE NameBloc='Mathematics'), (SELECT IDNotion from notion WHERE NameNotion='Differential equations')),
((SELECT IDBloc from bloc WHERE NameBloc='Functions study'), (SELECT IDNotion from notion WHERE NameNotion='Differential equations')),
((SELECT IDBloc from bloc WHERE NameBloc='Mathematics'), (SELECT IDNotion from notion WHERE NameNotion='Probabilities')),
((SELECT IDBloc from bloc WHERE NameBloc='Fundamental sciences'), (SELECT IDNotion from notion WHERE NameNotion='Probabilities')),
((SELECT IDBloc from bloc WHERE NameBloc='Functions study'), (SELECT IDNotion from notion WHERE NameNotion='Numeric sequences')),
((SELECT IDBloc from bloc WHERE NameBloc='Mathematics'), (SELECT IDNotion from notion WHERE NameNotion='Numeric sequences')),
((SELECT IDBloc from bloc WHERE NameBloc='Fundamental sciences'), (SELECT IDNotion from notion WHERE NameNotion='Numeric sequences')),
((SELECT IDBloc from bloc WHERE NameBloc='Mathematics'), (SELECT IDNotion from notion WHERE NameNotion='Complex numbers')),
((SELECT IDBloc from bloc WHERE NameBloc='Mathematics'), (SELECT IDNotion from notion WHERE NameNotion='Cartesian geometry')),
((SELECT IDBloc from bloc WHERE NameBloc='Mathematics'), (SELECT IDNotion from notion WHERE NameNotion='Vectorial geometry')),
((SELECT IDBloc from bloc WHERE NameBloc='Mathematics'), (SELECT IDNotion from notion WHERE NameNotion='Matrix')),
((SELECT IDBloc from bloc WHERE NameBloc='Mathematics'), (SELECT IDNotion from notion WHERE NameNotion='Arithmetics')),
((SELECT IDBloc from bloc WHERE NameBloc='Fundamental sciences'), (SELECT IDNotion from notion WHERE NameNotion='Matrix')),
((SELECT IDBloc from bloc WHERE NameBloc='Fundamental sciences'), (SELECT IDNotion from notion WHERE NameNotion='Arithmetics')),
((SELECT IDBloc from bloc WHERE NameBloc='Embedded systems'), (SELECT IDNotion from notion WHERE NameNotion='Embedded system')),
((SELECT IDBloc from bloc WHERE NameBloc='Embedded systems'), (SELECT IDNotion from notion WHERE NameNotion='C')),
((SELECT IDBloc from bloc WHERE NameBloc='Oriented Object Programming'), (SELECT IDNotion from notion WHERE NameNotion='Oriented Object Programming')),
((SELECT IDBloc from bloc WHERE NameBloc='Web development'), (SELECT IDNotion from notion WHERE NameNotion='Oriented Object Programming')),
((SELECT IDBloc from bloc WHERE NameBloc='Oriented Object Programming'), (SELECT IDNotion from notion WHERE NameNotion='C++')),
((SELECT IDBloc from bloc WHERE NameBloc='Oriented Object Programming'), (SELECT IDNotion from notion WHERE NameNotion='.NET')),
((SELECT IDBloc from bloc WHERE NameBloc='Oriented Object Programming'), (SELECT IDNotion from notion WHERE NameNotion='UML Conception')),
((SELECT IDBloc from bloc WHERE NameBloc='Embedded systems'), (SELECT IDNotion from notion WHERE NameNotion='UML Conception')),
((SELECT IDBloc from bloc WHERE NameBloc='Waves physics & signal'), (SELECT IDNotion from notion WHERE NameNotion='Procedural programming')),
((SELECT IDBloc from bloc WHERE NameBloc='Information systems & security'), (SELECT IDNotion from notion WHERE NameNotion='IS architecture & networks')),
((SELECT IDBloc from bloc WHERE NameBloc='SI Infrastructure & networks'), (SELECT IDNotion from notion WHERE NameNotion='IS architecture & networks')),
((SELECT IDBloc from bloc WHERE NameBloc='SI Infrastructure & networks'), (SELECT IDNotion from notion WHERE NameNotion='CCNA Certification')),
((SELECT IDBloc from bloc WHERE NameBloc='SI Infrastructure & networks'), (SELECT IDNotion from notion WHERE NameNotion='Cisco Packet Tracer')),
((SELECT IDBloc from bloc WHERE NameBloc='SI Infrastructure & networks'), (SELECT IDNotion from notion WHERE NameNotion='Cybersecurity')),
((SELECT IDBloc from bloc WHERE NameBloc='Information systems & security'), (SELECT IDNotion from notion WHERE NameNotion='Cybersecurity')),
((SELECT IDBloc from bloc WHERE NameBloc='Fundamental sciences'), (SELECT IDNotion from notion WHERE NameNotion='Game theory')),
((SELECT IDBloc from bloc WHERE NameBloc='Fundamental sciences'), (SELECT IDNotion from notion WHERE NameNotion='Programming Paradigms')),
((SELECT IDBloc from bloc WHERE NameBloc='Fundamental sciences'), (SELECT IDNotion from notion WHERE NameNotion='Cryptography')),
((SELECT IDBloc from bloc WHERE NameBloc='Fundamental sciences'), (SELECT IDNotion from notion WHERE NameNotion='Graph theory')),
((SELECT IDBloc from bloc WHERE NameBloc='Advanced algorithmics & combinatory'), (SELECT IDNotion from notion WHERE NameNotion='Programming Paradigms')),
((SELECT IDBloc from bloc WHERE NameBloc='SI Infrastructure & networks'), (SELECT IDNotion from notion WHERE NameNotion='Cryptography')),
((SELECT IDBloc from bloc WHERE NameBloc='Advanced algorithmics & combinatory'), (SELECT IDNotion from notion WHERE NameNotion='Graph theory')),
((SELECT IDBloc from bloc WHERE NameBloc='Databases'), (SELECT IDNotion from notion WHERE NameNotion='Database Mangement Systems')),
((SELECT IDBloc from bloc WHERE NameBloc='Information systems & security'), (SELECT IDNotion from notion WHERE NameNotion='Database Mangement Systems')),
((SELECT IDBloc from bloc WHERE NameBloc='Information systems & security'), (SELECT IDNotion from notion WHERE NameNotion='Group Policy Objects')),
((SELECT IDBloc from bloc WHERE NameBloc='Information systems & security'), (SELECT IDNotion from notion WHERE NameNotion='Cloud computing')),
((SELECT IDBloc from bloc WHERE NameBloc='SI Infrastructure & networks'), (SELECT IDNotion from notion WHERE NameNotion='Cloud computing')),
((SELECT IDBloc from bloc WHERE NameBloc='Advanced algorithmics & combinatory'), (SELECT IDNotion from notion WHERE NameNotion='Problem complexity')),
((SELECT IDBloc from bloc WHERE NameBloc='Advanced algorithmics & combinatory'), (SELECT IDNotion from notion WHERE NameNotion='Problem categories')),
((SELECT IDBloc from bloc WHERE NameBloc='Advanced algorithmics & combinatory'), (SELECT IDNotion from notion WHERE NameNotion='Heuristics & meta heuristics')),
((SELECT IDBloc from bloc WHERE NameBloc='Advanced algorithmics & combinatory'), (SELECT IDNotion from notion WHERE NameNotion='Linear programming')),
((SELECT IDBloc from bloc WHERE NameBloc='Advanced algorithmics & combinatory'), (SELECT IDNotion from notion WHERE NameNotion='Best solution search algorithms')),
((SELECT IDBloc from bloc WHERE NameBloc='Advanced algorithmics & combinatory'), (SELECT IDNotion from notion WHERE NameNotion='Operation Research')),
((SELECT IDBloc from bloc WHERE NameBloc='AI & machine learning'), (SELECT IDNotion from notion WHERE NameNotion='Machine learning')),
((SELECT IDBloc from bloc WHERE NameBloc='AI & machine learning'), (SELECT IDNotion from notion WHERE NameNotion='Data processing')),
((SELECT IDBloc from bloc WHERE NameBloc='AI & machine learning'), (SELECT IDNotion from notion WHERE NameNotion='Model creation & training')),
((SELECT IDBloc from bloc WHERE NameBloc='AI & machine learning'), (SELECT IDNotion from notion WHERE NameNotion='Model performance analysis')),
((SELECT IDBloc from bloc WHERE NameBloc='AI & machine learning'), (SELECT IDNotion from notion WHERE NameNotion='Regression models')),
((SELECT IDBloc from bloc WHERE NameBloc='AI & machine learning'), (SELECT IDNotion from notion WHERE NameNotion='Classifier models')),
((SELECT IDBloc from bloc WHERE NameBloc='Web development'), (SELECT IDNotion from notion WHERE NameNotion='HTML')),
((SELECT IDBloc from bloc WHERE NameBloc='Web development'), (SELECT IDNotion from notion WHERE NameNotion='CSS')),
((SELECT IDBloc from bloc WHERE NameBloc='Web development'), (SELECT IDNotion from notion WHERE NameNotion='JavaScript')),
((SELECT IDBloc from bloc WHERE NameBloc='Web development'), (SELECT IDNotion from notion WHERE NameNotion='PHP')),
((SELECT IDBloc from bloc WHERE NameBloc='Web development'), (SELECT IDNotion from notion WHERE NameNotion='Smarty')),
((SELECT IDBloc from bloc WHERE NameBloc='Web development'), (SELECT IDNotion from notion WHERE NameNotion='Rest APIs')),
((SELECT IDBloc from bloc WHERE NameBloc='Web development'), (SELECT IDNotion from notion WHERE NameNotion='UX/UI Design')),
((SELECT IDBloc from bloc WHERE NameBloc='Databases'), (SELECT IDNotion from notion WHERE NameNotion='English')),
((SELECT IDBloc from bloc WHERE NameBloc='Fundamental sciences'), (SELECT IDNotion from notion WHERE NameNotion='English')),
((SELECT IDBloc from bloc WHERE NameBloc='Information systems & security'), (SELECT IDNotion from notion WHERE NameNotion='English')),
((SELECT IDBloc from bloc WHERE NameBloc='Advanced algorithmics & combinatory'), (SELECT IDNotion from notion WHERE NameNotion='English')),
((SELECT IDBloc from bloc WHERE NameBloc='AI & machine learning'), (SELECT IDNotion from notion WHERE NameNotion='English')),
((SELECT IDBloc from bloc WHERE NameBloc='Software engineering'), (SELECT IDNotion from notion WHERE NameNotion='English')),
((SELECT IDBloc from bloc WHERE NameBloc='Big Data'), (SELECT IDNotion from notion WHERE NameNotion='English')),
((SELECT IDBloc from bloc WHERE NameBloc='English'), (SELECT IDNotion from notion WHERE NameNotion='English'));

INSERT INTO nopr (IDProject, IDNotion) 
VALUES ((SELECT IDProject from project WHERE NameProject='Safe tinkercad'), (SELECT IDNotion from notion WHERE NameNotion='Tinkercad')),
((SELECT IDProject from project WHERE NameProject='Safe tinkercad'), (SELECT IDNotion from notion WHERE NameNotion='Arduino Uno')),
((SELECT IDProject from project WHERE NameProject='World Wide Weather Watcher'), (SELECT IDNotion from notion WHERE NameNotion='Arduino Uno')),
((SELECT IDProject from project WHERE NameProject='Safe tinkercad'), (SELECT IDNotion from notion WHERE NameNotion='C Arduino')),
((SELECT IDProject from project WHERE NameProject='World Wide Weather Watcher'), (SELECT IDNotion from notion WHERE NameNotion='C Arduino')),
((SELECT IDProject from project WHERE NameProject='World Wide Weather Watcher'), (SELECT IDNotion from notion WHERE NameNotion='Continuous current')),
((SELECT IDProject from project WHERE NameProject='Safe tinkercad'), (SELECT IDNotion from notion WHERE NameNotion='Continuous current')),
((SELECT IDProject from project WHERE NameProject='Signal modulation'), (SELECT IDNotion from notion WHERE NameNotion='Alternating current')),
((SELECT IDProject from project WHERE NameProject='Signal modulation'), (SELECT IDNotion from notion WHERE NameNotion='Signal processing')),
((SELECT IDProject from project WHERE NameProject='Signal modulation'), (SELECT IDNotion from notion WHERE NameNotion='Python')),
((SELECT IDProject from project WHERE NameProject='Signal modulation'), (SELECT IDNotion from notion WHERE NameNotion='Jupyter Notebook')),
((SELECT IDProject from project WHERE NameProject='Container House'), (SELECT IDNotion from notion WHERE NameNotion='Laws of static')),
((SELECT IDProject from project WHERE NameProject='\'Fast&Furious\' case study'), (SELECT IDNotion from notion WHERE NameNotion='Laws of dynamic')),
((SELECT IDProject from project WHERE NameProject='\'Fast&Furious\' case study'), (SELECT IDNotion from notion WHERE NameNotion='Mechanics')),
((SELECT IDProject from project WHERE NameProject='SmartIO Box'), (SELECT IDNotion from notion WHERE NameNotion='Computer Aided Conception')),
((SELECT IDProject from project WHERE NameProject='SmartIO Box'), (SELECT IDNotion from notion WHERE NameNotion='Fusion360')),
((SELECT IDProject from project WHERE NameProject='SmartIO Box'), (SELECT IDNotion from notion WHERE NameNotion='3D printing')),
((SELECT IDProject from project WHERE NameProject='SmartIO Box'), (SELECT IDNotion from notion WHERE NameNotion='Cura')),
((SELECT IDProject from project WHERE NameProject='SmartIO Box'), (SELECT IDNotion from notion WHERE NameNotion='Lean management')),
((SELECT IDProject from project WHERE NameProject='StageFinder'), (SELECT IDNotion from notion WHERE NameNotion='MySQL')),
((SELECT IDProject from project WHERE NameProject='TODO Databases'), (SELECT IDNotion from notion WHERE NameNotion='MySQL')),
((SELECT IDProject from project WHERE NameProject='Oriented Object Programming TODO'), (SELECT IDNotion from notion WHERE NameNotion='MicrosoftSQL')),
((SELECT IDProject from project WHERE NameProject='TODO Databases'), (SELECT IDNotion from notion WHERE NameNotion='Relationnal Databases')),
((SELECT IDProject from project WHERE NameProject='StageFinder'), (SELECT IDNotion from notion WHERE NameNotion='Relationnal Databases')),
((SELECT IDProject from project WHERE NameProject='Oriented Object Programming TODO'), (SELECT IDNotion from notion WHERE NameNotion='Relationnal Databases')),
((SELECT IDProject from project WHERE NameProject='TODO Databases'), (SELECT IDNotion from notion WHERE NameNotion='Merise Method')),
((SELECT IDProject from project WHERE NameProject='TODO Databases'), (SELECT IDNotion from notion WHERE NameNotion='Data analysis')),
((SELECT IDProject from project WHERE NameProject='World Wide Weather Watcher'), (SELECT IDNotion from notion WHERE NameNotion='Data analysis')),
((SELECT IDProject from project WHERE NameProject='HumanForYou'), (SELECT IDNotion from notion WHERE NameNotion='Data analysis')),
((SELECT IDProject from project WHERE NameProject='HumanForYou'), (SELECT IDNotion from notion WHERE NameNotion='Statistics')),
((SELECT IDProject from project WHERE NameProject='Oriented Object Programming TODO'), (SELECT IDNotion from notion WHERE NameNotion='Statistics')),
((SELECT IDProject from project WHERE NameProject='Container House'), (SELECT IDNotion from notion WHERE NameNotion='Thermodynamics')),
((SELECT IDProject from project WHERE NameProject='Container House'), (SELECT IDNotion from notion WHERE NameNotion='Materials strenght')),
((SELECT IDProject from project WHERE NameProject='Container House'), (SELECT IDNotion from notion WHERE NameNotion='Revit')),
((SELECT IDProject from project WHERE NameProject='Container House'), (SELECT IDNotion from notion WHERE NameNotion='Differential equations')),
((SELECT IDProject from project WHERE NameProject='\'Fast&Furious\' case study'), (SELECT IDNotion from notion WHERE NameNotion='Differential equations')),
((SELECT IDProject from project WHERE NameProject='World Wide Weather Watcher'), (SELECT IDNotion from notion WHERE NameNotion='Embedded system')),
((SELECT IDProject from project WHERE NameProject='World Wide Weather Watcher'), (SELECT IDNotion from notion WHERE NameNotion='C')),
((SELECT IDProject from project WHERE NameProject='Oriented Object Programming TODO'), (SELECT IDNotion from notion WHERE NameNotion='Oriented Object Programming')),
((SELECT IDProject from project WHERE NameProject='StageFinder'), (SELECT IDNotion from notion WHERE NameNotion='Oriented Object Programming')),
((SELECT IDProject from project WHERE NameProject='Oriented Object Programming TODO'), (SELECT IDNotion from notion WHERE NameNotion='C++')),
((SELECT IDProject from project WHERE NameProject='Oriented Object Programming TODO'), (SELECT IDNotion from notion WHERE NameNotion='.NET')),
((SELECT IDProject from project WHERE NameProject='Oriented Object Programming TODO'), (SELECT IDNotion from notion WHERE NameNotion='UML Conception')),
((SELECT IDProject from project WHERE NameProject='World Wide Weather Watcher'), (SELECT IDNotion from notion WHERE NameNotion='UML Conception')),
((SELECT IDProject from project WHERE NameProject='Signal modulation'), (SELECT IDNotion from notion WHERE NameNotion='Procedural programming')),
((SELECT IDProject from project WHERE NameProject='FunkyTown'), (SELECT IDNotion from notion WHERE NameNotion='IS architecture & networks')),
((SELECT IDProject from project WHERE NameProject='FunkyTown'), (SELECT IDNotion from notion WHERE NameNotion='CCNA Certification')),
((SELECT IDProject from project WHERE NameProject='FunkyTown'), (SELECT IDNotion from notion WHERE NameNotion='Cisco Packet Tracer')),
((SELECT IDProject from project WHERE NameProject='FunkyTown'), (SELECT IDNotion from notion WHERE NameNotion='Cybersecurity')),
((SELECT IDProject from project WHERE NameProject='Vehicle Routing Problem'), (SELECT IDNotion from notion WHERE NameNotion='Programming Paradigms')),
((SELECT IDProject from project WHERE NameProject='FunkyTown'), (SELECT IDNotion from notion WHERE NameNotion='Cryptography')),
((SELECT IDProject from project WHERE NameProject='Vehicle Routing Problem'), (SELECT IDNotion from notion WHERE NameNotion='Graph theory')),
((SELECT IDProject from project WHERE NameProject='TODO Databases'), (SELECT IDNotion from notion WHERE NameNotion='Database Mangement Systems')),
((SELECT IDProject from project WHERE NameProject='FunkyTown'), (SELECT IDNotion from notion WHERE NameNotion='Cloud computing')),
((SELECT IDProject from project WHERE NameProject='Vehicle Routing Problem'), (SELECT IDNotion from notion WHERE NameNotion='Problem complexity')),
((SELECT IDProject from project WHERE NameProject='Vehicle Routing Problem'), (SELECT IDNotion from notion WHERE NameNotion='Problem categories')),
((SELECT IDProject from project WHERE NameProject='Vehicle Routing Problem'), (SELECT IDNotion from notion WHERE NameNotion='Heuristics & meta heuristics')),
((SELECT IDProject from project WHERE NameProject='Vehicle Routing Problem'), (SELECT IDNotion from notion WHERE NameNotion='Linear programming')),
((SELECT IDProject from project WHERE NameProject='Vehicle Routing Problem'), (SELECT IDNotion from notion WHERE NameNotion='Best solution search algorithms')),
((SELECT IDProject from project WHERE NameProject='Vehicle Routing Problem'), (SELECT IDNotion from notion WHERE NameNotion='Operation Research')),
((SELECT IDProject from project WHERE NameProject='HumanForYou'), (SELECT IDNotion from notion WHERE NameNotion='Machine learning')),
((SELECT IDProject from project WHERE NameProject='HumanForYou'), (SELECT IDNotion from notion WHERE NameNotion='Data processing')),
((SELECT IDProject from project WHERE NameProject='HumanForYou'), (SELECT IDNotion from notion WHERE NameNotion='Model creation & training')),
((SELECT IDProject from project WHERE NameProject='HumanForYou'), (SELECT IDNotion from notion WHERE NameNotion='Model performance analysis')),
((SELECT IDProject from project WHERE NameProject='HumanForYou'), (SELECT IDNotion from notion WHERE NameNotion='Regression models')),
((SELECT IDProject from project WHERE NameProject='HumanForYou'), (SELECT IDNotion from notion WHERE NameNotion='Classifier models')),
((SELECT IDProject from project WHERE NameProject='StageFinder'), (SELECT IDNotion from notion WHERE NameNotion='HTML')),
((SELECT IDProject from project WHERE NameProject='StageFinder'), (SELECT IDNotion from notion WHERE NameNotion='CSS')),
((SELECT IDProject from project WHERE NameProject='StageFinder'), (SELECT IDNotion from notion WHERE NameNotion='JavaScript')),
((SELECT IDProject from project WHERE NameProject='StageFinder'), (SELECT IDNotion from notion WHERE NameNotion='PHP')),
((SELECT IDProject from project WHERE NameProject='StageFinder'), (SELECT IDNotion from notion WHERE NameNotion='Smarty')),
((SELECT IDProject from project WHERE NameProject='StageFinder'), (SELECT IDNotion from notion WHERE NameNotion='Rest APIs')),
((SELECT IDProject from project WHERE NameProject='StageFinder'), (SELECT IDNotion from notion WHERE NameNotion='UX/UI Design')),
((SELECT IDProject from project WHERE NameProject='Portfolio Website'), (SELECT IDNotion from notion WHERE NameNotion='HTML')),
((SELECT IDProject from project WHERE NameProject='Portfolio Website'), (SELECT IDNotion from notion WHERE NameNotion='CSS')),
((SELECT IDProject from project WHERE NameProject='Portfolio Website'), (SELECT IDNotion from notion WHERE NameNotion='JavaScript')),
((SELECT IDProject from project WHERE NameProject='Portfolio Website'), (SELECT IDNotion from notion WHERE NameNotion='PHP')),
((SELECT IDProject from project WHERE NameProject='Portfolio Website'), (SELECT IDNotion from notion WHERE NameNotion='Rest APIs')),
((SELECT IDProject from project WHERE NameProject='Portfolio Website'), (SELECT IDNotion from notion WHERE NameNotion='UX/UI Design')),
((SELECT IDProject from project WHERE NameProject='Portfolio Website'), (SELECT IDNotion from notion WHERE NameNotion='Oriented Object Programming')),
((SELECT IDProject from project WHERE NameProject='Shepherd dog game'), (SELECT IDNotion from notion WHERE NameNotion='Oriented Object Programming')),
((SELECT IDProject from project WHERE NameProject='Shepherd dog game'), (SELECT IDNotion from notion WHERE NameNotion='C#')),
((SELECT IDProject from project WHERE NameProject='Shepherd dog game'), (SELECT IDNotion from notion WHERE NameNotion='Unity')),
((SELECT IDProject from project WHERE NameProject='Shepherd dog game'), (SELECT IDNotion from notion WHERE NameNotion='Blender'));